import { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import css from './styles/main.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <html
      lang="en"
      className="fullSize"
    >
      <body className="fullSize">{children}</body>
    </html>
  );
}
